### ISSUE TITLE
Crash with posixaio on Mac OS X 10.10.2

### ISSUE THREAD

**Issue by felixbuenemann** [axboe/fio#47]
fio segfaults on Mac OS X when trying to use the posixaio engine. I tried with current master:
```
uname -a
Darwin couchbook.lan 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix

cat rw.fio
[foo]
thread
ioengine=posixaio
rw=randwrite
iodepth=32
size=1024m
directory=/Users/felix/tmp/fio-1

~/bin/fio rw.fio
foo: (g=0): rw=randwrite, bs=4K-4K/4K-4K/4K-4K, ioengine=posixaio, iodepth=32
fio-2.2.5-11-gd47d
Starting 1 thread
foo: Laying out IO file(s) (1 file(s) / 1024MB)
fio: pid=2819, err=-1/file:engines/posixaio.c:213, func=xfer, error=Unknown error: -1
fio(45155,0x11084a000) malloc: *** error for object 0x7fbad8504500: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    45155 abort      ~/bin/fio rw.fio

lldb ~/bin/fio
(lldb) target create "/Users/felix/bin/fio"
Current executable set to '/Users/felix/bin/fio' (x86_64).
(lldb) r /Users/felix/tmp/rw.fio
Process 45124 launched: '/Users/felix/bin/fio' (x86_64)
foo: (g=0): rw=randwrite, bs=4K-4K/4K-4K/4K-4K, ioengine=posixaio, iodepth=32
fio-2.2.5-11-gd47d
Starting 1 thread
foo: Laying out IO file(s) (1 file(s) / 1024MB)
fio: pid=2819, err=-1/file:engines/posixaio.c:213, func=xfer, error=Unknown error: -1
fio(45124,0x10071c000) malloc: *** error for object 0x102104780: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Process 45124 stopped
* thread #2: tid = 0x45972, 0x00007fff8dd98286 libsystem_kernel.dylib`__pthread_kill + 10, stop reason = signal SIGABRT
    frame #0: 0x00007fff8dd98286 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill + 10:
-> 0x7fff8dd98286:  jae    0x7fff8dd98290            ; __pthread_kill + 20
   0x7fff8dd98288:  movq   %rax, %rdi
   0x7fff8dd9828b:  jmp    0x7fff8dd93c53            ; cerror_nocancel
   0x7fff8dd98290:  retq
(lldb) bt all
  thread #1: tid = 0x4594c, 0x00007fff8dd9848a libsystem_kernel.dylib`__semwait_signal + 10, queue = 'com.apple.main-thread'
    frame #0: 0x00007fff8dd9848a libsystem_kernel.dylib`__semwait_signal + 10
    frame #1: 0x00007fff8ffe9f5d libsystem_c.dylib`nanosleep + 199
    frame #2: 0x00007fff8ffe9e50 libsystem_c.dylib`usleep + 54
    frame #3: 0x0000000100033f42 fio`fio_backend [inlined] do_usleep(usecs=<unavailable>) + 2546 at backend.c:1831
    frame #4: 0x0000000100033f2e fio`fio_backend [inlined] run_threads + 2077 at backend.c:2073
    frame #5: 0x0000000100033711 fio`fio_backend + 449 at backend.c:2190
    frame #6: 0x00007fff9352c5c9 libdyld.dylib`start + 1

  thread #3: tid = 0x45971, 0x00007fff8dd98136 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #0: 0x00007fff8dd98136 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff8ba78e0c libsystem_pthread.dylib`_pthread_cond_wait + 693
    frame #2: 0x0000000100037781 fio`helper_thread_main(data=<unavailable>) + 145 at backend.c:2118
    frame #3: 0x00007fff8ba78268 libsystem_pthread.dylib`_pthread_body + 131
    frame #4: 0x00007fff8ba781e5 libsystem_pthread.dylib`_pthread_start + 176
    frame #5: 0x00007fff8ba7641d libsystem_pthread.dylib`thread_start + 13

* thread #2: tid = 0x45972, 0x00007fff8dd98286 libsystem_kernel.dylib`__pthread_kill + 10, stop reason = signal SIGABRT
  * frame #0: 0x00007fff8dd98286 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff8ba7a42f libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff8ffc8b53 libsystem_c.dylib`abort + 129
    frame #3: 0x00007fff960d5937 libsystem_malloc.dylib`free + 428
    frame #4: 0x00000001000348dc fio`thread_main [inlined] cleanup_io_u + 77 at backend.c:971
    frame #5: 0x000000010003488f fio`thread_main(data=0x0000000100400000) + 1951 at backend.c:1577
    frame #6: 0x00007fff8ba78268 libsystem_pthread.dylib`_pthread_body + 131
    frame #7: 0x00007fff8ba781e5 libsystem_pthread.dylib`_pthread_start + 176
    frame #8: 0x00007fff8ba7641d libsystem_pthread.dylib`thread_start + 13
(lldb)
```

**Comment by axboe** [comment]
Should be fixed.

**Comment by felixbuenemann** [comment]
The segfault is gone, thanks.

I'm still getting:
```
fio: pid=2819, err=-1/file:engines/posixaio.c:213, func=xfer, error=Unknown error: -1
```
Does that mean that posixaio cannot be used on OS X?

**Comment by axboe** [comment]
Same job file? Let me try OSX here.

**Comment by axboe** [comment]
OK, I see what that problem was. This should fix it:

http://git.kernel.dk/?p=fio.git;a=commit;h=138c0e22828cfb2993c382e8fdb54562fbc19005

Please pull again and retry, should work fine now.

**Comment by felixbuenemann** [comment]
Thanks, works fine now! :heart:

**Comment by axboe** [comment]
Perfect! Thanks for reporting and testing.
