### ISSUE TITLE
Warnings are repeated for each numjob

### ISSUE THREAD

**Issue by brycepg** [axboe/fio#532]
When using `numjobs=128` I'm seeing 128 `fio: only root may flush block devices. Cache flush bypassed!`, flooding the console. I think it would be a good idea to limit this message to only once per run.

**Comment by brycepg** [comment]
It looks like the code is attempting to limit the error. Somehow the static guard `root_warn` is being set to zero every time cache_invalidate is called: https://github.com/axboe/fio/blob/master/filesetup.c#L519

**Comment by axboe** [comment]
Fio has a bunch of these, it's intended to limit the error, but it ends up being a limit per-job. Easy enough to improve, let me push a few fixes for this that converts this and a few other similar call sites.

**Comment by axboe** [comment]
Done, please retest with current -git, you should only see the warning once. This is not totally race safe, but I doubt we'd ever hit that. If we do, you'd just get a spurious extra warning, which is no big deal.

**Comment by brycepg** [comment]
Thanks for looking into it @axboe .
It looks like the issue still persists. I think it's because each job is a process

**Comment by brycepg** [comment]
Would this require something like mmap? https://stackoverflow.com/questions/5656530/how-to-use-shared-memory-with-linux-in-c

**Comment by axboe** [comment]
I do know how shared memory works :-)

The state is shared in shared memory, but I messed up the logic in when to warn and when not to. Hence you probably got 127 warnings, instead of 1. Pushed the fix out.

**Comment by brycepg** [comment]
I know; I'm the one not very familiar with shared memory in C :)

It works! Thanks
