### ISSUE TITLE
fio compiled with -march=native is slower

### ISSUE THREAD

**Issue by AntonHPE** [axboe/fio#587]
Hello

Different fio versions show different results.  As example, for fio 3.3 vs 3.6 version with exactly the same I/O pattern,

  {
    "dev":"namespace3.0",
    "mode":"raw",
    "size":322122547200,
    "sector_size":512,
    "blockdev":"pmem3",
    "numa_node":3
  }

linux-zkms:~ # fio --version
fio-3.3
linux-zkms:/var/anton/fio-fio-3.3 # numactl --cpunodebind=3 --membind=3 fio --filename=/dev/pmem3 --rw=randread --direct=1 --ioengine=libaio --bs=4k --iodepth=1 --numjobs=16 --runtime=60 --group_reporting --name=perf_test
perf_test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
...
fio-3.3
Starting 16 processes
Jobs: 16 (f=16): [r(16)][100.0%][r=31.2GiB/s,w=0KiB/s][r=8186k,w=0 IOPS][eta 00m:00s]
perf_test: (groupid=0, jobs=16): err= 0: pid=20710: Sun Apr 22 05:10:14 2018
   read: IOPS=8248k, BW=31.5GiB/s (33.8GB/s)(1888GiB/60001msec)
    slat (nsec): min=1029, max=69400, avg=1298.46, stdev=370.67
    clat (nsec): min=165, max=60094, avg=188.62, stdev=129.45
     lat (nsec): min=1231, max=69928, avg=1521.56, stdev=398.68
    clat percentiles (nsec):
     |  1.00th=[  175],  5.00th=[  177], 10.00th=[  179], 20.00th=[  181],
     | 30.00th=[  183], 40.00th=[  185], 50.00th=[  185], 60.00th=[  187],
     | 70.00th=[  187], 80.00th=[  191], 90.00th=[  197], 95.00th=[  205],
     | 99.00th=[  251], 99.50th=[  270], 99.90th=[  362], 99.95th=[  418],
     | 99.99th=[ 4512]
   bw (  MiB/s): min= 1917, max= 2191, per=6.25%, avg=2014.56, stdev=37.79, samples=1904
   iops        : min=490790, max=560904, avg=515726.37, stdev=9674.83, samples=1904
  lat (nsec)   : 250=98.97%, 500=1.01%, 750=0.01%, 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=0.01%, 50=0.01%
  lat (usec)   : 100=0.01%
  cpu          : usr=32.03%, sys=67.98%, ctx=759, majf=0, minf=165
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=494912422,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=31.5GiB/s (33.8GB/s), 31.5GiB/s-31.5GiB/s (33.8GB/s-33.8GB/s), io=1888GiB (2027GB), run=60001-60001msec

linux-zkms:/var/anton/fio-fio-3.6 # fio --version
fio-3.6
linux-zkms:/var/anton/fio-fio-3.6 #
linux-zkms:/var/anton/fio-fio-3.6 # numactl --cpunodebind=3 --membind=3 fio --filename=/dev/pmem3 --rw=randread --direct=1 --ioengine=libaio --bs=4k --iodepth=1 --numjobs=16 --runtime=60 --group_reporting --name=perf_test
perf_test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
...
fio-3.6
Starting 16 processes
Jobs: 16 (f=16): [r(16)][100.0%][r=30.1GiB/s,w=0KiB/s][r=7894k,w=0 IOPS][eta 00m:00s]
perf_test: (groupid=0, jobs=16): err= 0: pid=16314: Sun Apr 22 05:01:07 2018
   read: IOPS=7924k, BW=30.2GiB/s (32.5GB/s)(1814GiB/60002msec)
    slat (nsec): min=1055, max=46499, avg=1359.98, stdev=376.06
    clat (nsec): min=174, max=55349, avg=208.39, stdev=136.06
     lat (nsec): min=1308, max=56658, avg=1607.64, stdev=406.62
    clat percentiles (nsec):
     |  1.00th=[  199],  5.00th=[  201], 10.00th=[  201], 20.00th=[  203],
     | 30.00th=[  203], 40.00th=[  203], 50.00th=[  205], 60.00th=[  205],
     | 70.00th=[  207], 80.00th=[  209], 90.00th=[  213], 95.00th=[  219],
     | 99.00th=[  278], 99.50th=[  294], 99.90th=[  410], 99.95th=[  458],
     | 99.99th=[ 4256]
   bw (  MiB/s): min= 1842, max= 2020, per=6.25%, avg=1934.50, stdev=34.28, samples=1905
   iops        : min=471744, max=517350, avg=495232.72, stdev=8775.66, samples=1905
  lat (nsec)   : 250=98.21%, 500=1.76%, 750=0.02%, 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=0.01%, 50=0.01%
  lat (usec)   : 100=0.01%
  cpu          : usr=31.24%, sys=68.76%, ctx=752, majf=0, minf=159
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=475446025,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=30.2GiB/s (32.5GB/s), 30.2GiB/s-30.2GiB/s (32.5GB/s-32.5GB/s), io=1814GiB (1947GB), run=60002-60002msec

Disk stats (read/write):
  pmem3: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%

**Comment by axboe** [comment]
If this is consistently reproducible, can you try and bisect and see what the offending commit is? Should not take very long. Let me know if you have questions about that process.

**Comment by AntonHPE** [comment]
>  If this is consistently reproducible

Yes.  It's  reproducible.  3.3 version is faster.

> can you try and bisect and see what the offending commit is

Sorry, is not clear to me what should I do here.  Can you clarify it please
?

2018-04-22 19:12 GMT+03:00 Jens Axboe <notifications@github.com>:

**Comment by sitsofe** [comment]
@AntonHPE 
> > can you try and bisect and see what the offending commit is
>
> Sorry, is not clear to me what should I do here.  Can you clarify it please
> ?

You can successively try the revision of fio halfway between the one that works and the one that doesn't until you (hopefully) get down to a single commit that introduced the issue (as hinted at we don't just mean released version but git commits). See https://blog.theodo.fr/2017/05/how-to-git-bisect-your-project/ for an example.

**Comment by axboe** [comment]
Basically what you do is:

$ git bisect start
$ git bisect good fio-3.3
$ git bisect bad fio-3.6

and then it spits out a revision for you to test. You run make clean && make for each one, then run your test case. If the result is good (high perf), you do:

$ git bisect good

If not, you do:

$ git bisect bad

Continue this until git tells you what the bad revision is, and then paste that here.

**Comment by AntonHPE** [comment]
Is it ok marked in yellow below,

linux-zkms:/var/anton # git bisect start

fatal: Not a git repository (or any parent up to mount point /)

Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

linux-zkms:/var/anton # git init

Initialized empty Git repository in /var/anton/.git/

linux-zkms:/var/anton # git bisect start

linux-zkms:/var/anton # git bisect good fio-3.3

fatal: Needed a single revision

Bad rev input: fio-3.3


2018-04-23 17:54 GMT+03:00 Jens Axboe <notifications@github.com>:

**Comment by axboe** [comment]
You have to have a fio git repo, the bisect works on that. I'm assuming you can build fio on the box? If not, you'll have to do the git bisect on a different box and copy each built instance of fio over for the test run that decides good/bad for bisect.

Before doing the bisect start, you'd do:

```
$ git clone git://git.kernel.dk/fio
```

and ensure that you have the dependencies to build fio with what you need. Also see the link Sitsofe provided, or maybe this one: https://stackoverflow.com/questions/4713088/how-to-use-git-bisect

**Comment by AntonHPE** [comment]
>

$ git clone git://git.kernel.dk/fio


it doesn't work as you can see below.  Instead it works from another source.


linux-zkms:/var/anton # git clone git://git.kernel.dk/fio
Cloning into 'fio'...
^C
linux-zkms:/var/anton # git clone https://github.com/axboe/fio.git
Cloning into 'fio'...
remote: Counting objects: 26929, done.
remote: Total 26929 (delta 0), reused 0 (delta 0), pack-reused 26929
Receiving objects: 100% (26929/26929), 17.26 MiB | 15.42 MiB/s, done.
Resolving deltas: 100% (17795/17795), done.
linux-zkms:/var/anton # git bisect start
fatal: invalid reference: master
Checking out 'master' failed. Try 'git bisect reset <valid-branch>'.
linux-zkms:/var/anton # cd fio
linux-zkms:/var/anton/fio # git bisect start
linux-zkms:/var/anton/fio # git bisect good fio-3.3
linux-zkms:/var/anton/fio # git bisect bad fio-3.6
Bisecting: 87 revisions left to test after this (roughly 7 steps)
[ec370c22ae525e127e23f7f77c423f21a6a73bbb] io_u: 'is_random' can be a
boolean
linux-zkms:/var/anton/fio #


2018-04-28 16:43 GMT+03:00 Jens Axboe <notifications@github.com>:

**Comment by sitsofe** [comment]
@AntonHPE The git:// protocol might be blocked on your network hence why your first command didn't work. As for the second - you didn't cd into the the directory (./fio) the git clone created before you started issuing git commands...

**Comment by axboe** [comment]
Any progress on this?

**Comment by AntonHPE** [comment]
Not yet.  We had an issue with access to the box.  It was network/cable
issue.  Just fixed that.  So I will resume on this this evening or tomorrow.

2018-05-04 17:52 GMT+03:00 Jens Axboe <notifications@github.com>:

**Comment by AntonHPE** [comment]
Originally it was,



but now on fio3.3* I can't get the same numbers.  The biggest jump occurs
on 3.5 version,

linux-zkms:/var/anton/fio # numactl --cpunodebind=3 --membind=3 fio
--filename=/dev/pmem3 --rw=randread --direct=1 --ioengine=libaio --bs=4k
--iodepth=1 --numjobs=16 --runtime=60 --group_reporting --name=perf_test
perf_test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T)
4096B-4096B, ioengine=libaio, iodepth=1
...
fio-3.5-20-ga817
Starting 16 processes
Jobs: 16 (f=16): [r(16)][100.0%][r=29.2GiB/s,w=0KiB/s][r=7657k,w=0
IOPS][eta 00m:00s]
perf_test: (groupid=0, jobs=16): err= 0: pid=22049: Sat May  5 15:04:46 2018
   read: IOPS=7708k, BW=29.4GiB/s (31.6GB/s)(1764GiB/60002msec)
    slat (nsec): min=1067, max=57173, avg=1375.52, stdev=321.76
    clat (nsec): min=177, max=38372, avg=217.66, stdev=115.08
     lat (nsec): min=1321, max=58243, avg=1631.48, stdev=347.65
    clat percentiles (nsec):
     |  1.00th=[  205],  5.00th=[  207], 10.00th=[  209], 20.00th=[  211],
     | 30.00th=[  211], 40.00th=[  213], 50.00th=[  215], 60.00th=[  217],
     | 70.00th=[  219], 80.00th=[  221], 90.00th=[  225], 95.00th=[  229],
     | 99.00th=[  286], 99.50th=[  298], 99.90th=[  390], 99.95th=[  442],
     | 99.99th=[ 3696]
   bw (  MiB/s): min= 1808, max= 1958, per=6.25%, avg=1882.19, stdev=23.74,
samples=1906
   iops        : min=462874, max=501434, avg=481840.87, stdev=6076.26,
samples=1906
  lat (nsec)   : 250=98.23%, 500=1.75%, 750=0.02%, 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=0.01%, 50=0.01%
  cpu          : usr=32.83%, sys=67.17%, ctx=757, majf=0, minf=173
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%,
>=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%,
>=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%,
>=64=0.0%
     issued rwts: total=462491679,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=29.4GiB/s (31.6GB/s), 29.4GiB/s-29.4GiB/s (31.6GB/s-31.6GB/s),
io=1764GiB (1894GB), run=60002-60002msec

Disk stats (read/write):
  pmem3: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
linux-zkms:/var/anton/fio # git bisect bad
............................................................................

linux-zkms:/var/anton/fio # numactl --cpunodebind=3 --membind=3 fio
--filename=/dev/pmem3 --rw=randread --direct=1 --ioengine=libaio --bs=4k
--iodepth=1 --numjobs=16 --runtime=60 --group_reporting --name=perf_test
perf_test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T)
4096B-4096B, ioengine=libaio, iodepth=1
...
fio-3.5-18-gb979
Starting 16 processes
Jobs: 16 (f=16): [r(16)][100.0%][r=31.5GiB/s,w=0KiB/s][r=8262k,w=0
IOPS][eta 00m:00s]
perf_test: (groupid=0, jobs=16): err= 0: pid=26452: Sat May  5 15:09:16 2018
   read: IOPS=8307k, BW=31.7GiB/s (34.0GB/s)(1901GiB/60003msec)
    slat (nsec): min=1015, max=54428, avg=1294.46, stdev=340.24
    clat (nsec): min=164, max=54804, avg=186.04, stdev=116.15
     lat (nsec): min=1220, max=56061, avg=1515.72, stdev=365.47
    clat percentiles (nsec):
     |  1.00th=[  173],  5.00th=[  175], 10.00th=[  179], 20.00th=[  181],
     | 30.00th=[  181], 40.00th=[  183], 50.00th=[  183], 60.00th=[  185],
     | 70.00th=[  185], 80.00th=[  187], 90.00th=[  191], 95.00th=[  197],
     | 99.00th=[  251], 99.50th=[  270], 99.90th=[  374], 99.95th=[  430],
     | 99.99th=[  908]
   bw (  MiB/s): min= 1924, max= 2225, per=6.25%, avg=2028.93, stdev=40.54,
samples=1908
   iops        : min=492730, max=569714, avg=519405.83, stdev=10377.48,
samples=1908
  lat (nsec)   : 250=98.92%, 500=1.06%, 750=0.01%, 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=0.01%, 50=0.01%
  lat (usec)   : 100=0.01%
  cpu          : usr=32.30%, sys=67.70%, ctx=762, majf=0, minf=181
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%,
>=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%,
>=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%,
>=64=0.0%
     issued rwts: total=498462168,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=31.7GiB/s (34.0GB/s), 31.7GiB/s-31.7GiB/s (34.0GB/s-34.0GB/s),
io=1901GiB (2042GB), run=60003-60003msec

Disk stats (read/write):
  pmem3: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%

linux-zkms:/var/anton/fio # git bisect good
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[825b0a75ded0b3bec4d70ea8ea50af3cad7abab5] Don't make fadvise failure fatal
linux-zkms:/var/anton/fio #
linux-zkms:/var/anton/fio # numactl --cpunodebind=3 --membind=3 fio
--filename=/dev/pmem3 --rw=randread --direct=1 --ioengine=libaio --bs=4k
--iodepth=1 --numjobs=16 --runtime=60 --group_reporting --name=perf_test
perf_test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T)
4096B-4096B, ioengine=libaio, iodepth=1
...
fio-3.5-19-g825b
Starting 16 processes
Jobs: 16 (f=16): [r(16)][100.0%][r=31.4GiB/s,w=0KiB/s][r=8239k,w=0
IOPS][eta 00m:00s]
perf_test: (groupid=0, jobs=16): err= 0: pid=28654: Sat May  5 15:11:44 2018
   read: IOPS=8301k, BW=31.7GiB/s (34.0GB/s)(1900GiB/60001msec)
    slat (nsec): min=1023, max=57652, avg=1292.79, stdev=350.95
    clat (nsec): min=163, max=44811, avg=187.63, stdev=120.08
     lat (nsec): min=1230, max=58638, avg=1515.60, stdev=376.96
    clat percentiles (nsec):
     |  1.00th=[  173],  5.00th=[  177], 10.00th=[  179], 20.00th=[  181],
     | 30.00th=[  183], 40.00th=[  185], 50.00th=[  185], 60.00th=[  187],
     | 70.00th=[  187], 80.00th=[  189], 90.00th=[  193], 95.00th=[  197],
     | 99.00th=[  249], 99.50th=[  266], 99.90th=[  362], 99.95th=[  418],
     | 99.99th=[ 4080]
   bw (  MiB/s): min= 1931, max= 2219, per=6.25%, avg=2027.14, stdev=39.41,
samples=1904
   iops        : min=494482, max=568166, avg=518946.99, stdev=10088.51,
samples=1904
  lat (nsec)   : 250=99.02%, 500=0.96%, 750=0.01%, 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=0.01%, 50=0.01%
  cpu          : usr=32.11%, sys=67.90%, ctx=747, majf=0, minf=162
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%,
>=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%,
>=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%,
>=64=0.0%
     issued rwts: total=498070429,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=31.7GiB/s (34.0GB/s), 31.7GiB/s-31.7GiB/s (34.0GB/s-34.0GB/s),
io=1900GiB (2040GB), run=60001-60001msec

Disk stats (read/write):
  pmem3: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
linux-zkms:/var/anton/fio #

linux-zkms:/var/anton/fio # git bisect good
a817dc3b3b5a0efc95aaca366875eac67607cd5b is the first bad commit
commit a817dc3b3b5a0efc95aaca366875eac67607cd5b
Author: Jens Axboe <axboe@kernel.dk>
Date:   Tue Mar 6 14:28:16 2018 -0700

    Default to building native code

    If the local compiler supports it, use -march=native to ensure we
    take full advantage of a local build.

    If building distro packages, or otherwise for a different platform
    than the host, then use --disable-native with configure to remove
    this optimization.

    Signed-off-by: Jens Axboe <axboe@kernel.dk>

:100644 100644 c25b4222e43729a2ca961718158470acaa807b52
19ba40a078703d58e77ab8f877b30fb86b6af384 M      Makefile
:100755 100755 2e8eb180ef50b20db7996c3bbac3e1f5330940fe
eb673adc22c083fc59ec7184f473d7776fed9684 M      configure
linux-zkms:/var/anton/fio #

2018-05-04 19:33 GMT+03:00 Anton Gavriliuk <antosha20xx@gmail.com>:

**Comment by axboe** [comment]
Two questions:

1) Are you building it on the host you are running it on?
2) If you do ```git revert a817dc3``` is it then faster for you?

**Comment by AntonHPE** [comment]
> Are you building it on the host you are running it on?

Yes, it is 4 Intel xeon sockets HPE DL560 G10 box -
https://www.hpe.com/us/en/product-catalog/servers/proliant-servers/pip.hpe-proliant-dl560-gen10-server.1010026837.html
running on SLES15 RC2

> If you do git revert a817dc3 is it then faster for you?

From which point I have to do " git revert a817dc3 " ?, as after I sent you
previous mail I tried latest fio 3.6*

2018-05-06 2:01 GMT+03:00 Jens Axboe <notifications@github.com>:

**Comment by sitsofe** [comment]
@AntonHPE One thing you can try is this:

```
git checkout a817dc3b3b5a0efc95aaca366875eac67607cd5b
./configure
make clean
./configure
make
[etc]
```

Check that you trigger the issue. Then

```
git revert a817dc3b3b5a0efc95aaca366875eac67607cd5b
make clean
./configure
make
[etc]
```

Check to see if issue goes away.

If you feel happy fixing up the fall out you can even do things like:

```
git checkout origin/master
make clean
./configure
make
[etc]
```

Check you see the issue. Then

```
git revert a817dc3
[manually fix up the fall out e.g. by deleting the whole of the conflicting regions]
make clean
./configure
make
[etc]
```

Then see if the issue goes away.

**Comment by AntonHPE** [comment]
> git checkout a817dc3b3b5a0efc95aaca366875eac67607cd5b

linux-zkms:/var/anton # git checkout
a817dc3b3b5a0efc95aaca366875eac67607cd5b fatal: reference is not a tree:
a817dc3b3b5a0efc95aaca366875eac67607cd5b linux-zkms:/var/anton #

Should I run git clone... before ?

2018-05-06 18:13 GMT+03:00 Sitsofe Wheeler <notifications@github.com>:

**Comment by axboe** [comment]
You have to be in the fio git directory...

**Comment by AntonHPE** [comment]
> @AntonHPE <https://github.com/AntonHPE> One thing you can try is this:

> git checkout a817dc3b3b5a0efc95aaca366875eac67607cd5b
> ./configure
> make clean
> ./configure
> make
> [etc]

> Check that you trigger the issue. Then

Yes there is the issue,

linux-zkms:/var/anton/fio # numactl --cpunodebind=3 --membind=3 fio
--filename=/dev/pmem3 --rw=randread --direct=1 --ioengine=libaio --bs=4k
--iodepth=1 --numjobs=16 --runtime=60 --group_reporting --name=perf_test

perf_test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T)
4096B-4096B, ioengine=libaio, iodepth=1

...

fio-3.5-20-ga817

Starting 16 processes

Jobs: 16 (f=16): [r(16)][100.0%][r=29.2GiB/s,w=0KiB/s][r=7664k,w=0
IOPS][eta 00m:00s]

perf_test: (groupid=0, jobs=16): err= 0: pid=30255: Tue May  8 14:31:33 2018

   read: IOPS=7716k, BW=29.4GiB/s (31.6GB/s)(1766GiB/60001msec)

    slat (nsec): min=1042, max=94040, avg=1371.73, stdev=365.31

    clat (nsec): min=181, max=54423, avg=221.17, stdev=135.40

     lat (nsec): min=1324, max=95117, avg=1631.39, stdev=396.38
> > git revert a817dc3
> > [manually fix up the fall out e.g. by deleting the whole of the
conflicting regions]
> > make clean
> > ./configure
> > make
> > [etc]
> >
> > Then see if the issue goes away.

Yes, the issue goes away.

linux-zkms:/var/anton/fio # numactl --cpunodebind=3 --membind=3 fio
--filename=/dev/pmem3 --rw=randread --direct=1 --ioengine=libaio --bs=4k
--iodepth=1 --numjobs=16 --runtime=60 --group_reporting --name=perf_test

perf_test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T)
4096B-4096B, ioengine=libaio, iodepth=1

...

fio-3.5-21-ga87d

Starting 16 processes

Jobs: 16 (f=16): [r(16)][100.0%][r=31.5GiB/s,w=0KiB/s][r=8248k,w=0
IOPS][eta 00m:00s]

perf_test: (groupid=0, jobs=16): err= 0: pid=32683: Tue May  8 14:38:19 2018

   read: IOPS=8310k, BW=31.7GiB/s (34.0GB/s)(1902GiB/60001msec)

    slat (nsec): min=1017, max=91899, avg=1293.62, stdev=228.72

    clat (nsec): min=164, max=55852, avg=190.20, stdev=70.13

     lat (nsec): min=1223, max=93005, avg=1519.13, stdev=243.17

2018-05-07 0:40 GMT+03:00 Jens Axboe <notifications@github.com>:

> You have to be in the fio git directory...
>

**Comment by AntonHPE** [comment]
Done, it still slower again,

linux-zkms:/var/anton/fio #
login as: root
Using keyboard-interactive authentication.
Password:
Last login: Tue May  8 14:17:39 2018 from 10.251.70.18
linux-zkms:~ # cd /var/anton/fio
linux-zkms:/var/anton/fio # git checkout a817dc3
Warning: you are leaving 1 commit behind, not connected to
any of your branches:

  a87d28d2 Revert "Default to building native code"

If you want to keep it by creating a new branch, this may be a good time
to do so with:

 git branch <new-branch-name> a87d28d2

HEAD is now at a817dc3b Default to building native code
linux-zkms:/var/anton/fio # make clean
FIO_VERSION = fio-3.5-20-ga817
linux-zkms:/var/anton/fio # ./configure
Operating system              Linux
CPU                           x86_64
Big endian                    no
Compiler                      gcc
Cross compile                 no

Static build                  no
Wordsize                      64
zlib                          yes
Linux AIO support             yes
POSIX AIO support             yes
POSIX AIO support needs -lrt  yes
POSIX AIO fsync               yes
POSIX pshared support         yes
Solaris AIO support           no
__sync_fetch_and_add          yes
__sync_synchronize            yes
__sync_val_compare_and_swap   yes
libverbs                      no
rdmacm                        no
Linux fallocate               yes
POSIX fadvise                 yes
POSIX fallocate               yes
sched_setaffinity(3 arg)      yes
sched_setaffinity(2 arg)      no
clock_gettime                 yes
CLOCK_MONOTONIC               yes
CLOCK_MONOTONIC_RAW           yes
CLOCK_MONOTONIC_PRECISE       no
clockid_t                     yes
gettimeofday                  yes
fdatasync                     yes
sync_file_range               yes
EXT4 move extent              yes
Linux splice(2)               yes
GUASI                         no
Fusion-io atomic engine       no
libnuma                       no
strsep                        yes
strcasestr                    yes
strlcat                       no
getopt_long_only()            yes
inet_aton                     yes
socklen_t                     yes
__thread                      yes
RUSAGE_THREAD                 yes
SCHED_IDLE                    yes
TCP_NODELAY                   yes
Net engine window_size        yes
TCP_MAXSEG                    yes
RLIMIT_MEMLOCK                yes
pwritev/preadv                yes
pwritev2/preadv2              yes
IPv6 helpers                  yes
Rados engine                  no
Rados Block Device engine     no
rbd blkin tracing             no
setvbuf                       yes
Gluster API engine            no
s390_z196_facilities          no
HDFS engine                   no
MTD                           yes
libpmem                       yes
libpmemblk                    yes
NVML pmemblk engine           yes
NVML dev-dax engine           yes
NVML libpmem engine           yes
lex/yacc for arithmetic       no
getmntent                     yes
getmntinfo                    no
Static Assert                 yes
bool                          yes
strndup                       yes
march_armv8_a_crc_crypto      no
cuda                          no
mkdir(a, b)                   yes
Build march=native            yes
linux-zkms:/var/anton/fio # make
FIO_VERSION = fio-3.5-20-ga817
    CC crc/crc16.o
    CC crc/crc32.o
    CC crc/crc32c-arm64.o
    CC crc/crc32c-intel.o
    CC crc/crc32c.o
    CC crc/crc64.o
    CC crc/crc7.o
    CC crc/fnv.o
    CC crc/md5.o
    CC crc/murmur3.o
    CC crc/sha1.o
    CC crc/sha256.o
    CC crc/sha3.o
    CC crc/sha512.o
    CC crc/test.o
    CC crc/xxhash.o
    CC lib/axmap.o
    CC lib/bloom.o
    CC lib/flist_sort.o
    CC lib/gauss.o
    CC lib/getrusage.o
    CC lib/hweight.o
    CC lib/ieee754.o
    CC lib/lfsr.o
    CC lib/memalign.o
    CC lib/memcpy.o
    CC lib/mountcheck.o
    CC lib/num2str.o
    CC lib/output_buffer.o
    CC lib/pattern.o
    CC lib/prio_tree.o
    CC lib/rand.o
    CC lib/rbtree.o
    CC lib/strntol.o
    CC lib/zipf.o
    CC gettime.o
    CC ioengines.o
    CC init.o
    CC stat.o
    CC log.o
    CC time.o
    CC filesetup.o
    CC eta.o
    CC verify.o
    CC memory.o
    CC io_u.o
    CC parse.o
    CC mutex.o
    CC options.o
    CC smalloc.o
    CC filehash.o
    CC profile.o
    CC debug.o
    CC engines/cpu.o
    CC engines/mmap.o
    CC engines/sync.o
    CC engines/null.o
    CC engines/net.o
    CC engines/ftruncate.o
    CC engines/filecreate.o
    CC server.o
    CC client.o
    CC iolog.o
    CC backend.o
    CC libfio.o
    CC flow.o
    CC cconv.o
    CC gettime-thread.o
    CC helpers.o
    CC json.o
    CC idletime.o
    CC td_error.o
    CC profiles/tiobench.o
    CC profiles/act.o
    CC io_u_queue.o
    CC filelock.o
    CC workqueue.o
    CC rate-submit.o
    CC optgroup.o
    CC helper_thread.o
    CC steadystate.o
    CC engines/libaio.o
    CC engines/posixaio.o
    CC engines/falloc.o
    CC engines/e4defrag.o
    CC engines/splice.o
    CC oslib/strlcat.o
    CC engines/mtd.o
    CC oslib/libmtd.o
    CC oslib/libmtd_legacy.o
    CC engines/pmemblk.o
    CC engines/dev-dax.o
    CC engines/libpmem.o
    CC diskutil.o
    CC fifo.o
    CC blktrace.o
    CC cgroup.o
    CC trim.o
    CC engines/sg.o
    CC engines/binject.o
    CC oslib/linux-dev-lookup.o
    CC fio.o
  LINK fio
    CC t/log.o
    CC t/genzipf.o
    CC oslib/strcasestr.o
    CC oslib/strndup.o
  LINK t/fio-genzipf
    CC t/btrace2fio.o
  LINK t/fio-btrace2fio
    CC t/dedupe.o
    CC t/debug.o
    CC t/arch.o
  LINK t/fio-dedupe
    CC t/verify-state.o
  LINK t/fio-verify-state
    CC t/stest.o
  LINK t/stest
    CC t/ieee754.o
  LINK t/ieee754
    CC t/axmap.o
  LINK t/axmap
    CC t/lfsr-test.o
  LINK t/lfsr-test
    CC t/gen-rand.o
  LINK t/gen-rand
linux-zkms:/var/anton/fio # make install
install -m 755 -d /usr/local/bin
install fio t/fio-genzipf t/fio-btrace2fio t/fio-dedupe t/fio-verify-state
./tools/fio_generate_plots ./tools/plot/fio2gnuplot ./tools/genfio
./tools/fiologparser.py ./tools/hist/fiologparser_hist.py
./tools/fio_jsonplus_clat2csv /usr/local/bin
install -m 755 -d /usr/local/man/man1
install -m 644 ./fio.1 /usr/local/man/man1
install -m 644 ./tools/fio_generate_plots.1 /usr/local/man/man1
install -m 644 ./tools/plot/fio2gnuplot.1 /usr/local/man/man1
install -m 644 ./tools/hist/fiologparser_hist.py.1 /usr/local/man/man1
install -m 755 -d /usr/local/share/fio
install -m 644 ./tools/plot/*gpm /usr/local/share/fio/
linux-zkms:/var/anton/fio # LD_BIND_NOW=1 numactl --cpunodebind=3
--membind=3 fio --filename=/dev/pmem3 --rw=randread --direct=1
--ioengine=libaio --bs=4k --iodepth=1 --numjobs=16 --runtime=60
--group_reporting --name=perf_test
perf_test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T)
4096B-4096B, ioengine=libaio, iodepth=1
...
fio-3.5-20-ga817
Starting 16 processes
Jobs: 16 (f=16): [r(16)][100.0%][r=29.3GiB/s,w=0KiB/s][r=7681k,w=0
IOPS][eta 00m:00s]
perf_test: (groupid=0, jobs=16): err= 0: pid=45540: Thu May 10 03:36:15 2018
   read: IOPS=7731k, BW=29.5GiB/s (31.7GB/s)(1770GiB/60001msec)
    slat (nsec): min=1043, max=62063, avg=1373.68, stdev=393.03
    clat (nsec): min=175, max=33983, avg=215.52, stdev=142.35
     lat (nsec): min=1301, max=63387, avg=1627.64, stdev=425.20
    clat percentiles (nsec):
     |  1.00th=[  205],  5.00th=[  205], 10.00th=[  207], 20.00th=[  209],
     | 30.00th=[  211], 40.00th=[  211], 50.00th=[  213], 60.00th=[  213],
     | 70.00th=[  215], 80.00th=[  217], 90.00th=[  219], 95.00th=[  225],
     | 99.00th=[  282], 99.50th=[  298], 99.90th=[  390], 99.95th=[  450],
     | 99.99th=[ 4704]
   bw (  MiB/s): min= 1828, max= 1964, per=6.25%, avg=1887.87, stdev=26.00,
samples=1904
   iops        : min=468222, max=502978, avg=483294.38, stdev=6655.30,
samples=1904
  lat (nsec)   : 250=98.31%, 500=1.67%, 750=0.01%, 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=0.01%, 50=0.01%
  cpu          : usr=32.78%, sys=67.22%, ctx=763, majf=0, minf=163
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%,
>=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%,
>=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%,
>=64=0.0%
     issued rwts: total=463888232,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=29.5GiB/s (31.7GB/s), 29.5GiB/s-29.5GiB/s (31.7GB/s-31.7GB/s),
io=1770GiB (1900GB), run=60001-60001msec

Disk stats (read/write):
  pmem3: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
linux-zkms:/var/anton/fio #

2018-05-09 8:22 GMT+03:00 Sitsofe Wheeler <notifications@github.com>:

**Comment by sitsofe** [comment]
@AntonHPE Hmm, I still can't wondering if this is https://sourceware.org/bugzilla/show_bug.cgi?id=20495 . What distro and what version of glibc are you using? One more thing to try while you're inside the fio directory:

```
git checkout a817dc3
make clean
sed -i 's/=native/& -mno-avx/' Makefile 
./configure
make
[etc]
```

and then run your binary as normal.

**Comment by axboe** [comment]
That’s a very valid concern. It can also cause cores to run at a lower frequency. Anton, can you test this please?

**Comment by axboe** [comment]
Might also make sense to use -O2 with march=native, if it is the register issue. As to the frequency issued I alluded to earlier, I've seen this with AVX loading up cores and causing it to use a lower turbo frequency.

Anton, can you try variants of:

-march=native -O2
-march=native -mno-avx
-march=native -O3
-march=native -O3 -mno-avx

You can do this on current git (or 3.6 release), just edit the Makefile and edit around line 30 where it says:

```
ifndef CONFIG_FIO_NO_OPT                                                        
  CFLAGS += -O3 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2                           
endif                                                                           
ifdef CONFIG_BUILD_NATIVE                                                       
  CFLAGS += -march=native                                                       
endif
```
After each edit, be sure to run ```make clean && make``` to ensure everything is rebuilt with the new optimization flags.

**Comment by AntonHPE** [comment]
> What distro and what version of glibc are you using? One more thing to
try while you're inside the fio directory:

git checkout a817dc3
make clean
sed -i 's/=native/& -mno-avx/' Makefile
./configure
make
[etc]

> and then run your binary as normal.

I'm using SLES 15 RC2 currently, glibc version is 2.26.  With the
instructions above it's even slower than we have saw for the I/O pattern,

linux-zkms:/var/anton # cd fio

linux-zkms:/var/anton/fio # git checkout a817dc3

HEAD is now at a817dc3b Default to building native code

linux-zkms:/var/anton/fio # make clean

linux-zkms:/var/anton/fio # sed -i 's/=native/& -mno-avx/' Makefile

linux-zkms:/var/anton/fio # ./configure

Operating system              Linux

CPU                           x86_64

Big endian                    no

Compiler                      gcc

Cross compile                 no


Static build                  no

Wordsize                      64

zlib                          yes

Linux AIO support             yes

POSIX AIO support             yes

POSIX AIO support needs -lrt  yes

POSIX AIO fsync               yes

POSIX pshared support         yes

Solaris AIO support           no

__sync_fetch_and_add          yes

__sync_synchronize            yes

__sync_val_compare_and_swap   yes

libverbs                      no

rdmacm                        no

Linux fallocate               yes

POSIX fadvise                 yes

POSIX fallocate               yes

sched_setaffinity(3 arg)      yes

sched_setaffinity(2 arg)      no

clock_gettime                 yes

CLOCK_MONOTONIC               yes

CLOCK_MONOTONIC_RAW           yes

CLOCK_MONOTONIC_PRECISE       no

clockid_t                     yes

gettimeofday                  yes

fdatasync                     yes

sync_file_range               yes

EXT4 move extent              yes

Linux splice(2)               yes

GUASI                         no

Fusion-io atomic engine       no

libnuma                       no

strsep                        yes

strcasestr                    yes

strlcat                       no

getopt_long_only()            yes

inet_aton                     yes

socklen_t                     yes

__thread                      yes

RUSAGE_THREAD                 yes

SCHED_IDLE                    yes

TCP_NODELAY                   yes

Net engine window_size        yes

TCP_MAXSEG                    yes

RLIMIT_MEMLOCK                yes

pwritev/preadv                yes

pwritev2/preadv2              yes

IPv6 helpers                  yes

Rados engine                  no

Rados Block Device engine     no

rbd blkin tracing             no

setvbuf                       yes

Gluster API engine            no

s390_z196_facilities          no

HDFS engine                   no

MTD                           yes

libpmem                       yes

libpmemblk                    yes

NVML pmemblk engine           yes

NVML dev-dax engine           yes

NVML libpmem engine           yes

lex/yacc for arithmetic       no

getmntent                     yes

getmntinfo                    no

Static Assert                 yes

bool                          yes

strndup                       yes

march_armv8_a_crc_crypto      no

cuda                          no

mkdir(a, b)                   yes

Build march=native            yes

linux-zkms:/var/anton/fio # make

FIO_VERSION = fio-3.5-20-ga817-dirty

    CC crc/crc16.o

    CC crc/crc32.o

    CC crc/crc32c-arm64.o

    CC crc/crc32c-intel.o

    CC crc/crc32c.o

    CC crc/crc64.o

    CC crc/crc7.o

    CC crc/fnv.o

    CC crc/md5.o

    CC crc/murmur3.o

    CC crc/sha1.o

    CC crc/sha256.o

    CC crc/sha3.o

    CC crc/sha512.o

    CC crc/test.o

    CC crc/xxhash.o

    CC lib/axmap.o

    CC lib/bloom.o

    CC lib/flist_sort.o

    CC lib/gauss.o

    CC lib/getrusage.o

    CC lib/hweight.o

    CC lib/ieee754.o

    CC lib/lfsr.o

    CC lib/memalign.o

    CC lib/memcpy.o

    CC lib/mountcheck.o

    CC lib/num2str.o

    CC lib/output_buffer.o

    CC lib/pattern.o

    CC lib/prio_tree.o

    CC lib/rand.o

    CC lib/rbtree.o

    CC lib/strntol.o

    CC lib/zipf.o

    CC gettime.o

    CC ioengines.o

    CC init.o

    CC stat.o

    CC log.o

    CC time.o

    CC filesetup.o

    CC eta.o

    CC verify.o

    CC memory.o

    CC io_u.o

    CC parse.o

    CC mutex.o

    CC options.o

    CC smalloc.o

    CC filehash.o

    CC profile.o

    CC debug.o

    CC engines/cpu.o

    CC engines/mmap.o

    CC engines/sync.o

    CC engines/null.o

    CC engines/net.o

    CC engines/ftruncate.o

    CC engines/filecreate.o

    CC server.o

    CC client.o

    CC iolog.o

    CC backend.o

    CC libfio.o

    CC flow.o

    CC cconv.o

    CC gettime-thread.o

    CC helpers.o

    CC json.o

    CC idletime.o

    CC td_error.o

    CC profiles/tiobench.o

    CC profiles/act.o

    CC io_u_queue.o

    CC filelock.o

    CC workqueue.o

    CC rate-submit.o

    CC optgroup.o

    CC helper_thread.o

    CC steadystate.o

    CC engines/libaio.o

    CC engines/posixaio.o

    CC engines/falloc.o

    CC engines/e4defrag.o

    CC engines/splice.o

    CC oslib/strlcat.o

    CC engines/mtd.o

    CC oslib/libmtd.o

    CC oslib/libmtd_legacy.o

    CC engines/pmemblk.o

    CC engines/dev-dax.o

    CC engines/libpmem.o

    CC diskutil.o

    CC fifo.o

    CC blktrace.o

    CC cgroup.o

    CC trim.o

    CC engines/sg.o

    CC engines/binject.o

    CC oslib/linux-dev-lookup.o

    CC fio.o

  LINK fio

    CC t/log.o

    CC t/genzipf.o

    CC oslib/strcasestr.o

    CC oslib/strndup.o

  LINK t/fio-genzipf

    CC t/btrace2fio.o

  LINK t/fio-btrace2fio

    CC t/dedupe.o

    CC t/debug.o

    CC t/arch.o

  LINK t/fio-dedupe

    CC t/verify-state.o

  LINK t/fio-verify-state

    CC t/stest.o

  LINK t/stest

    CC t/ieee754.o

  LINK t/ieee754

    CC t/axmap.o

  LINK t/axmap

    CC t/lfsr-test.o

  LINK t/lfsr-test

    CC t/gen-rand.o

  LINK t/gen-rand

linux-zkms:/var/anton/fio # make install

install -m 755 -d /usr/local/bin

install fio t/fio-genzipf t/fio-btrace2fio t/fio-dedupe t/fio-verify-state
./tools/fio_generate_plots ./tools/plot/fio2gnuplot ./tools/genfio
./tools/fiologparser.py ./tools/hist/fiologparser_hist.py
./tools/fio_jsonplus_clat2csv /usr/local/bin

install -m 755 -d /usr/local/man/man1

install -m 644 ./fio.1 /usr/local/man/man1

install -m 644 ./tools/fio_generate_plots.1 /usr/local/man/man1

install -m 644 ./tools/plot/fio2gnuplot.1 /usr/local/man/man1

install -m 644 ./tools/hist/fiologparser_hist.py.1 /usr/local/man/man1

install -m 755 -d /usr/local/share/fio

install -m 644 ./tools/plot/*gpm /usr/local/share/fio/

linux-zkms:/var/anton/fio # numactl --cpunodebind=3 --membind=3 fio
--filename=/dev/pmem3 --rw=randread --direct=1 --ioengine=libaio --bs=4k
--iodepth=1 --numjobs=16 --runtime=60 --group_reporting --name=perf_test

perf_test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T)
4096B-4096B, ioengine=libaio, iodepth=1

...

fio-3.5-20-ga817-dirty

Starting 16 processes

Jobs: 16 (f=16): [r(16)][100.0%][r=24.4GiB/s,w=0KiB/s][r=6404k,w=0
IOPS][eta 00m:00s]

perf_test: (groupid=0, jobs=16): err= 0: pid=5693: Tue May 15 02:50:19 2018

   read: IOPS=6260k, BW=23.9GiB/s (25.6GB/s)(1433GiB/60001msec)

    slat (nsec): min=1358, max=52904, avg=1734.64, stdev=496.31

    clat (nsec): min=354, max=58237, avg=398.35, stdev=219.23

     lat (nsec): min=1788, max=60201, avg=2168.29, stdev=548.65

    clat percentiles (nsec):

     |  1.00th=[  374],  5.00th=[  378], 10.00th=[  382], 20.00th=[  386],

     | 30.00th=[  390], 40.00th=[  394], 50.00th=[  394], 60.00th=[  398],

     | 70.00th=[  398], 80.00th=[  402], 90.00th=[  406], 95.00th=[  410],

     | 99.00th=[  458], 99.50th=[  482], 99.90th=[  580], 99.95th=[  668],

     | 99.99th=[15936]

   bw (  MiB/s): min= 1322, max= 1600, per=6.25%, avg=1528.44, stdev=54.38,
samples=1904

   iops        : min=338546, max=409740, avg=391280.11, stdev=13920.92,
samples=1904

  lat (nsec)   : 500=99.68%, 750=0.28%, 1000=0.01%

  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=0.02%, 50=0.01%

  lat (usec)   : 100=0.01%

  cpu          : usr=29.31%, sys=70.69%, ctx=766, majf=0, minf=181

  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%,
>=64=0.0%

     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%,
>=64=0.0%

     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%,
>=64=0.0%

     issued rwts: total=375591249,0,0,0 short=0,0,0,0 dropped=0,0,0,0

     latency   : target=0, window=0, percentile=100.00%, depth=1


Run status group 0 (all jobs):

   READ: bw=23.9GiB/s (25.6GB/s), 23.9GiB/s-23.9GiB/s (25.6GB/s-25.6GB/s),
io=1433GiB (1538GB), run=60001-60001msec


Disk stats (read/write):

  pmem3: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%

linux-zkms:/var/anton/fio #

2018-05-12 19:40 GMT+03:00 Jens Axboe <notifications@github.com>:

**Comment by sitsofe** [comment]
@AntonHPE I've just tried reproducing this on Ubuntu 18.04 (gcc is Ubuntu 7.3.0-27ubuntu1~18.04) running on a Broadwell system with the following:
```
numactl --cpunodebind=1 --membind=1 ./fio --name=test --filename /dev/mapper/zero1  --rw=randread --direct=1 --ioengine=libaio --bs=4k --iodepth=1 --numjobs=16 --runtime=60 --group_reporting
```

but fio-3.3 and fio-3.6 give the same result for me as does using march=native compared to without march on 3.6. Note I don't get near the speed you do (the system I was using did about 13.5GiB/s).

Are you still interested in diagnosing this? If so I guess if it's still happening then we need to turn gcc features off. What's the output of:
```
diff <(gcc -O3 -Q --help=target) <(gcc -O3 -march=native -Q --help=target)
```

?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
