### ISSUE TITLE
random writes and verification

### ISSUE THREAD

**Issue by msquare27** [axboe/fio#713]
Hi,

I am doing random writes with verify_state_save=1 

fio --ioengine=libaio --name=test --direct=1 --filename=/dev/sdc --bs=8k --iodepth=1 --readwrite=randwrite --size=100% --numjobs=1 --verify=sha1 --do_verify=1 --verify_state_save=1 --group_reporting

And then verifying it here and hitting this error

[root@localhost fio]#fio --ioengine=libaio --name=test --direct=1 --filename=/dev/sdc --bs=8k --iodepth=1 --readwrite=read --size=100% --numjobs=1 --verify=sha1 --group_reporting --verify_only --verify_dump=1 --verify_state_load=1
fio-3.12
Starting 1 process
verify: bad magic header 0, wanted acca at file /dev/sdc offset 0, length 8192 (requested block: offset=0, length=8192)
       hdr_fail data dumped as sdc.0.hdr_fail
test: No I/O performed by libaio, perhaps try --debug=io option for details?
fio: pid=24698, err=84/file:io_u.c:2068, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character

test: (groupid=0, jobs=1): err=84 (file:io_u.c:2068, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character): pid=24698: Wed Nov 14 10:02:47 2018
  read: IOPS=1000, BW=8000KiB/s (8192kB/s)(8192B/1msec)

**Comment by msquare27** [comment]
I am using FIO version 3.12 

[root@localhost fio]# fio -v
fio-3.12

**Comment by sitsofe** [comment]
@msquare27 Hi, as this isn't so much an issue in fio and more of a "How do I/Why is?" question it is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.10/README#L58) (note that the list only accepts plain text emails).

Note your question looks very similar to answered on the mailing list: https://www.spinics.net/lists/fio/msg07622.html ...

**Comment by msquare27** [comment]
Hi,

I am not the same user who posted this https://www.spinics.net/lists/fio/msg07622.html

This is not the same as my issue. Here he is doing a mic if write/read and verify_state.

I am doing write and verify. It works absolutely fine when the writes are sequential and fails when it's random writes.

I will also send an email in the mailing list.

Much Thanks,
M

**Comment by msquare27** [comment]
Thank you for helping me out. I have corrected my command such that they rw parameter matches. I now have these

Write phase:
fio --ioengine=libaio --name=test --direct=1 --filename=/dev/sdc --bs=8k --iodepth=1 --readwrite=randwrite --size=100% --numjobs=1 --verify=sha1 --do_verify=1 --verify_state_save=1 --group_reporting

Verify phase:
fio --ioengine=libaio --name=test --direct=1 --filename=/dev/sdc --bs=8k --iodepth=1 --readwrite=randwrite --size=100% --numjobs=1 --verify=sha1 --group_reporting --verify_only --verify_dump=1 --verify_state_load=1 --do_verify=1

Readwrite parameter is set to randwrite in both. But I am still getting verification failure with

fio: pid=26599, err=84/file:io_u.c:2068, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character

Please do let me know if there is anything else I am missing.

**Comment by axboe** [comment]
Your setup still doesn't make sense. Your first command will write THEN verify the data. Your second invocation is nonsensical. I suspect what you want is:

ONLY do the writes
fio --ioengine=libaio --name=test --direct=1 --filename=/dev/sdc --bs=8k --iodepth=1 --readwrite=randwrite --size=100% --numjobs=1 --verify=sha1 --do_verify=0 --verify_state_save=1 --group_reporting

ONLY do verify reads
fio --ioengine=libaio --name=test --direct=1 --filename=/dev/sdc --bs=8k --iodepth=1 --readwrite=randread --size=100% --numjobs=1 --verify=sha1 --do_verify=1 --verify_state_save=1 --group_reporting

**Comment by msquare27** [comment]
Thanks for your previous reply @axboe

**Comment by sitsofe** [comment]
I think a minor tweak is using `--verify_state_load=1`  9https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify-state-load ) during the verify stage...

**Comment by msquare27** [comment]
This works with or without backlog option. Thanks for your help. 

In your reply, in the verify phase, you gave --verify_state_save=1 but it should have been --verify_state_load=1.

Thanks you so much for your help.



Write phase:
fio --ioengine=libaio --name=test --direct=1 --filename=/dev/sdc --bs=8k --iodepth=1 --readwrite=randwrite --size=100% --numjobs=1 --verify=sha1 --do_verify=1 --verify_state_save=1 --group_reporting --verify_backlog=1024

Verify phase 

fio --ioengine=libaio --name=test --direct=1 --filename=/dev/sdc --bs=8k --iodepth=1 --readwrite=randread --size=100% --numjobs=1 --verify=sha1 --group_reporting --verify_only --verify_dump=1 --verify_state_load=1 --do_verify=1 --verify_backlog=1024

**Comment by sitsofe** [comment]
@msquare27 If your questions have been answered could you close this issue? Thanks!
